"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEPTH = exports.OPEN_ORDERS = exports.ORDER_CANCELLED = exports.ORDER_PLACED = exports.ORDER_UPDATE = exports.TRADE_ADDED = exports.GET_OPEN_ORDERS = exports.GET_DEPTH = exports.ON_RAMP = exports.CANCEL_ORDER = exports.CREATE_ORDER = void 0;
exports.CREATE_ORDER = "CREATE_ORDER";
exports.CANCEL_ORDER = "CANCEL_ORDER";
exports.ON_RAMP = "ON_RAMP";
exports.GET_DEPTH = "GET_DEPTH";
exports.GET_OPEN_ORDERS = "GET_OPEN_ORDERS";
exports.TRADE_ADDED = "TRADE_ADDED";
exports.ORDER_UPDATE = "ORDER_UPDATE";
exports.ORDER_PLACED = "ORDER_PLACED";
exports.ORDER_CANCELLED = "ORDER_CANCELLED";
exports.OPEN_ORDERS = "OPEN_ORDERS";
exports.DEPTH = "DEPTH";
